import type {
  Client,
  Employee,
  Order,
  InventoryItem,
  Service,
  Invoice,
  Transaction,
  User,
} from "./types";

export const mockUser: User = {
  id: "user-1",
  email: "admin@coreapp.com",
  name: "John Anderson",
  companyName: "TechFix Pro Services",
  role: "admin",
};

export const mockClients: Client[] = [
  {
    id: "client-1",
    name: "Sarah Mitchell",
    email: "sarah.mitchell@email.com",
    phone: "+1 (555) 123-4567",
    address: "123 Oak Street, Suite 100, Boston, MA 02101",
    balance: 0,
    createdAt: "2024-01-15",
    notes: "VIP customer, prefers email communication",
  },
  {
    id: "client-2",
    name: "Michael Chen",
    email: "mchen@techcorp.com",
    phone: "+1 (555) 234-5678",
    address: "456 Pine Avenue, New York, NY 10001",
    balance: 250,
    createdAt: "2024-02-20",
  },
  {
    id: "client-3",
    name: "Emily Rodriguez",
    email: "emily.r@gmail.com",
    phone: "+1 (555) 345-6789",
    address: "789 Maple Drive, Chicago, IL 60601",
    balance: 0,
    createdAt: "2024-03-05",
  },
  {
    id: "client-4",
    name: "David Kim",
    email: "dkim@enterprise.io",
    phone: "+1 (555) 456-7890",
    address: "321 Cedar Lane, San Francisco, CA 94102",
    balance: 175,
    createdAt: "2024-03-18",
  },
  {
    id: "client-5",
    name: "Jessica Thompson",
    email: "jthompson@startup.co",
    phone: "+1 (555) 567-8901",
    address: "654 Birch Road, Austin, TX 78701",
    balance: 0,
    createdAt: "2024-04-02",
  },
  {
    id: "client-6",
    name: "Robert Williams",
    email: "rwilliams@corp.net",
    phone: "+1 (555) 678-9012",
    address: "987 Elm Street, Seattle, WA 98101",
    balance: 500,
    createdAt: "2024-04-15",
  },
  {
    id: "client-7",
    name: "Amanda Foster",
    email: "afoster@design.studio",
    phone: "+1 (555) 789-0123",
    address: "147 Willow Way, Miami, FL 33101",
    balance: 0,
    createdAt: "2024-05-01",
  },
  {
    id: "client-8",
    name: "James Patterson",
    email: "jpatterson@media.com",
    phone: "+1 (555) 890-1234",
    address: "258 Spruce Court, Denver, CO 80201",
    balance: 125,
    createdAt: "2024-05-20",
  },
  {
    id: "client-9",
    name: "Lisa Chang",
    email: "lchang@solutions.biz",
    phone: "+1 (555) 901-2345",
    address: "369 Aspen Circle, Portland, OR 97201",
    balance: 0,
    createdAt: "2024-06-08",
  },
  {
    id: "client-10",
    name: "Mark Johnson",
    email: "mjohnson@retail.com",
    phone: "+1 (555) 012-3456",
    address: "741 Redwood Boulevard, Phoenix, AZ 85001",
    balance: 75,
    createdAt: "2024-06-25",
  },
];

export const mockEmployees: Employee[] = [
  {
    id: "emp-1",
    name: "John Anderson",
    email: "john@coreapp.com",
    phone: "+1 (555) 111-1111",
    role: "admin",
    assignedTasks: 5,
    completedTasks: 142,
    status: "active",
  },
  {
    id: "emp-2",
    name: "Maria Garcia",
    email: "maria@coreapp.com",
    phone: "+1 (555) 222-2222",
    role: "manager",
    assignedTasks: 8,
    completedTasks: 98,
    status: "active",
  },
  {
    id: "emp-3",
    name: "Alex Turner",
    email: "alex@coreapp.com",
    phone: "+1 (555) 333-3333",
    role: "technician",
    assignedTasks: 12,
    completedTasks: 215,
    status: "active",
  },
  {
    id: "emp-4",
    name: "Sophie Brown",
    email: "sophie@coreapp.com",
    phone: "+1 (555) 444-4444",
    role: "technician",
    assignedTasks: 9,
    completedTasks: 187,
    status: "active",
  },
  {
    id: "emp-5",
    name: "Ryan Davis",
    email: "ryan@coreapp.com",
    phone: "+1 (555) 555-5555",
    role: "receptionist",
    assignedTasks: 3,
    completedTasks: 45,
    status: "active",
  },
  {
    id: "emp-6",
    name: "Nina Patel",
    email: "nina@coreapp.com",
    phone: "+1 (555) 666-6666",
    role: "technician",
    assignedTasks: 0,
    completedTasks: 76,
    status: "inactive",
  },
];

export const mockOrders: Order[] = [
  {
    id: "order-1",
    orderNumber: "ORD-2024-001",
    clientId: "client-1",
    clientName: "Sarah Mitchell",
    device: "iPhone 14 Pro",
    service: "Screen Replacement",
    description: "Cracked screen, needs full display replacement",
    status: "in-progress",
    assignedEmployeeId: "emp-3",
    assignedEmployeeName: "Alex Turner",
    deadline: "2024-07-05",
    totalPrice: 299,
    paymentStatus: "unpaid",
    createdAt: "2024-07-01",
    updatedAt: "2024-07-02",
  },
  {
    id: "order-2",
    orderNumber: "ORD-2024-002",
    clientId: "client-2",
    clientName: "Michael Chen",
    device: 'MacBook Pro 16"',
    service: "Battery Replacement",
    description: "Battery not holding charge, replace battery",
    status: "waiting-parts",
    assignedEmployeeId: "emp-4",
    assignedEmployeeName: "Sophie Brown",
    deadline: "2024-07-08",
    totalPrice: 199,
    paymentStatus: "partial",
    createdAt: "2024-07-01",
    updatedAt: "2024-07-03",
  },
  {
    id: "order-3",
    orderNumber: "ORD-2024-003",
    clientId: "client-3",
    clientName: "Emily Rodriguez",
    device: "Samsung Galaxy S24",
    service: "Diagnostics",
    description: "Phone randomly restarts, needs diagnostics",
    status: "new",
    assignedEmployeeId: "emp-3",
    assignedEmployeeName: "Alex Turner",
    deadline: "2024-07-04",
    totalPrice: 49,
    paymentStatus: "unpaid",
    createdAt: "2024-07-03",
    updatedAt: "2024-07-03",
  },
  {
    id: "order-4",
    orderNumber: "ORD-2024-004",
    clientId: "client-4",
    clientName: "David Kim",
    device: 'iPad Pro 12.9"',
    service: "Screen Replacement",
    description: "Damaged screen with dead pixels",
    status: "completed",
    assignedEmployeeId: "emp-4",
    assignedEmployeeName: "Sophie Brown",
    deadline: "2024-07-02",
    totalPrice: 449,
    paymentStatus: "paid",
    createdAt: "2024-06-28",
    updatedAt: "2024-07-02",
  },
  {
    id: "order-5",
    orderNumber: "ORD-2024-005",
    clientId: "client-5",
    clientName: "Jessica Thompson",
    device: "Dell XPS 15",
    service: "Software Installation",
    description: "Windows reinstall and software setup",
    status: "paid",
    assignedEmployeeId: "emp-3",
    assignedEmployeeName: "Alex Turner",
    deadline: "2024-06-30",
    totalPrice: 149,
    paymentStatus: "paid",
    createdAt: "2024-06-25",
    updatedAt: "2024-06-30",
  },
  {
    id: "order-6",
    orderNumber: "ORD-2024-006",
    clientId: "client-6",
    clientName: "Robert Williams",
    device: "iPhone 13",
    service: "Battery Replacement",
    description: "Battery health at 72%, needs replacement",
    status: "in-progress",
    assignedEmployeeId: "emp-4",
    assignedEmployeeName: "Sophie Brown",
    deadline: "2024-07-06",
    totalPrice: 89,
    paymentStatus: "unpaid",
    createdAt: "2024-07-02",
    updatedAt: "2024-07-03",
  },
  {
    id: "order-7",
    orderNumber: "ORD-2024-007",
    clientId: "client-7",
    clientName: "Amanda Foster",
    device: 'iMac 27"',
    service: "Hardware Upgrade",
    description: "RAM upgrade from 8GB to 32GB",
    status: "new",
    assignedEmployeeId: "emp-3",
    assignedEmployeeName: "Alex Turner",
    deadline: "2024-07-07",
    totalPrice: 249,
    paymentStatus: "unpaid",
    createdAt: "2024-07-03",
    updatedAt: "2024-07-03",
  },
  {
    id: "order-8",
    orderNumber: "ORD-2024-008",
    clientId: "client-8",
    clientName: "James Patterson",
    device: "Google Pixel 8",
    service: "Screen Replacement",
    description: "Cracked screen with touch issues",
    status: "cancelled",
    assignedEmployeeId: "emp-4",
    assignedEmployeeName: "Sophie Brown",
    deadline: "2024-07-05",
    totalPrice: 229,
    paymentStatus: "unpaid",
    createdAt: "2024-07-01",
    updatedAt: "2024-07-02",
  },
  {
    id: "order-9",
    orderNumber: "ORD-2024-009",
    clientId: "client-9",
    clientName: "Lisa Chang",
    device: "MacBook Air M2",
    service: "Diagnostics",
    description: "Keyboard not responding on some keys",
    status: "in-progress",
    assignedEmployeeId: "emp-3",
    assignedEmployeeName: "Alex Turner",
    deadline: "2024-07-04",
    totalPrice: 49,
    paymentStatus: "paid",
    createdAt: "2024-07-02",
    updatedAt: "2024-07-03",
  },
  {
    id: "order-10",
    orderNumber: "ORD-2024-010",
    clientId: "client-10",
    clientName: "Mark Johnson",
    device: "HP Spectre x360",
    service: "Data Recovery",
    description: "SSD failed, attempting data recovery",
    status: "waiting-parts",
    assignedEmployeeId: "emp-4",
    assignedEmployeeName: "Sophie Brown",
    deadline: "2024-07-10",
    totalPrice: 399,
    paymentStatus: "partial",
    createdAt: "2024-07-01",
    updatedAt: "2024-07-03",
  },
  {
    id: "order-11",
    orderNumber: "ORD-2024-011",
    clientId: "client-1",
    clientName: "Sarah Mitchell",
    device: "Apple Watch Series 9",
    service: "Screen Replacement",
    description: "Cracked watch screen",
    status: "completed",
    assignedEmployeeId: "emp-3",
    assignedEmployeeName: "Alex Turner",
    deadline: "2024-07-01",
    totalPrice: 179,
    paymentStatus: "paid",
    createdAt: "2024-06-28",
    updatedAt: "2024-07-01",
  },
  {
    id: "order-12",
    orderNumber: "ORD-2024-012",
    clientId: "client-2",
    clientName: "Michael Chen",
    device: "Surface Pro 9",
    service: "Software Installation",
    description: "Office suite and development tools setup",
    status: "new",
    assignedEmployeeId: "emp-4",
    assignedEmployeeName: "Sophie Brown",
    deadline: "2024-07-05",
    totalPrice: 99,
    paymentStatus: "unpaid",
    createdAt: "2024-07-03",
    updatedAt: "2024-07-03",
  },
];

export const mockInventory: InventoryItem[] = [
  {
    id: "inv-1",
    sku: "SCR-IPH14-BLK",
    name: "iPhone 14 Pro Screen Assembly - Black",
    category: "Screens",
    supplier: "TechParts Direct",
    quantity: 8,
    minQuantity: 5,
    purchasePrice: 120,
    salePrice: 199,
    status: "in-stock",
  },
  {
    id: "inv-2",
    sku: "BAT-IPH13-OEM",
    name: "iPhone 13 Battery - OEM",
    category: "Batteries",
    supplier: "Apple Parts Co",
    quantity: 15,
    minQuantity: 10,
    purchasePrice: 35,
    salePrice: 59,
    status: "in-stock",
  },
  {
    id: "inv-3",
    sku: "SCR-SAM-S24",
    name: "Samsung Galaxy S24 Screen",
    category: "Screens",
    supplier: "Samsung Wholesale",
    quantity: 3,
    minQuantity: 5,
    purchasePrice: 150,
    salePrice: 249,
    status: "low-stock",
  },
  {
    id: "inv-4",
    sku: "BAT-MBP16-2023",
    name: 'MacBook Pro 16" Battery 2023',
    category: "Batteries",
    supplier: "Apple Parts Co",
    quantity: 6,
    minQuantity: 3,
    purchasePrice: 80,
    salePrice: 149,
    status: "in-stock",
  },
  {
    id: "inv-5",
    sku: "CHG-USB-C-65W",
    name: "USB-C Charger 65W",
    category: "Accessories",
    supplier: "Power Solutions",
    quantity: 25,
    minQuantity: 10,
    purchasePrice: 15,
    salePrice: 35,
    status: "in-stock",
  },
  {
    id: "inv-6",
    sku: "SCR-IPAD-PRO12",
    name: 'iPad Pro 12.9" Screen Assembly',
    category: "Screens",
    supplier: "TechParts Direct",
    quantity: 2,
    minQuantity: 3,
    purchasePrice: 250,
    salePrice: 399,
    status: "low-stock",
  },
  {
    id: "inv-7",
    sku: "SSD-NVM-1TB",
    name: "NVMe SSD 1TB - Universal",
    category: "Storage",
    supplier: "Storage Depot",
    quantity: 12,
    minQuantity: 5,
    purchasePrice: 65,
    salePrice: 119,
    status: "in-stock",
  },
  {
    id: "inv-8",
    sku: "RAM-DDR5-16GB",
    name: "DDR5 RAM 16GB Module",
    category: "Memory",
    supplier: "Memory Masters",
    quantity: 0,
    minQuantity: 4,
    purchasePrice: 55,
    salePrice: 99,
    status: "out-of-stock",
  },
  {
    id: "inv-9",
    sku: "TOOL-KIT-PRO",
    name: "Professional Repair Tool Kit",
    category: "Tools",
    supplier: "ToolBox Inc",
    quantity: 5,
    minQuantity: 2,
    purchasePrice: 45,
    salePrice: 79,
    status: "in-stock",
  },
  {
    id: "inv-10",
    sku: "CBL-LGHT-1M",
    name: "Lightning Cable 1m - MFi",
    category: "Accessories",
    supplier: "Cable World",
    quantity: 50,
    minQuantity: 20,
    purchasePrice: 5,
    salePrice: 15,
    status: "in-stock",
  },
  {
    id: "inv-11",
    sku: "SCR-PIX8-PRO",
    name: "Google Pixel 8 Pro Screen",
    category: "Screens",
    supplier: "TechParts Direct",
    quantity: 4,
    minQuantity: 3,
    purchasePrice: 140,
    salePrice: 229,
    status: "in-stock",
  },
  {
    id: "inv-12",
    sku: "THM-PASTE-PRO",
    name: "Thermal Paste - Premium",
    category: "Tools",
    supplier: "CoolTech Supply",
    quantity: 20,
    minQuantity: 10,
    purchasePrice: 8,
    salePrice: 18,
    status: "in-stock",
  },
  {
    id: "inv-13",
    sku: "BAT-AW-S9",
    name: "Apple Watch Series 9 Battery",
    category: "Batteries",
    supplier: "Apple Parts Co",
    quantity: 1,
    minQuantity: 3,
    purchasePrice: 25,
    salePrice: 49,
    status: "low-stock",
  },
  {
    id: "inv-14",
    sku: "CASE-IPH15-CLR",
    name: "iPhone 15 Clear Case",
    category: "Accessories",
    supplier: "Case Factory",
    quantity: 35,
    minQuantity: 15,
    purchasePrice: 3,
    salePrice: 12,
    status: "in-stock",
  },
  {
    id: "inv-15",
    sku: "SPK-MBP-SET",
    name: "MacBook Pro Speaker Set",
    category: "Components",
    supplier: "Apple Parts Co",
    quantity: 7,
    minQuantity: 3,
    purchasePrice: 40,
    salePrice: 79,
    status: "in-stock",
  },
];

export const mockServices: Service[] = [
  {
    id: "svc-1",
    name: "Screen Replacement",
    category: "Repair",
    duration: 60,
    price: 199,
    description: "Full screen assembly replacement for smartphones and tablets",
    status: "active",
  },
  {
    id: "svc-2",
    name: "Battery Replacement",
    category: "Repair",
    duration: 30,
    price: 79,
    description: "Battery replacement for all device types",
    status: "active",
  },
  {
    id: "svc-3",
    name: "Diagnostics",
    category: "Assessment",
    duration: 30,
    price: 49,
    description: "Complete device diagnostics and issue identification",
    status: "active",
  },
  {
    id: "svc-4",
    name: "Software Installation",
    category: "Software",
    duration: 45,
    price: 99,
    description: "OS reinstall, software setup, and configuration",
    status: "active",
  },
  {
    id: "svc-5",
    name: "Data Recovery",
    category: "Data",
    duration: 120,
    price: 299,
    description: "Data recovery from failed drives and devices",
    status: "active",
  },
  {
    id: "svc-6",
    name: "Hardware Upgrade",
    category: "Upgrade",
    duration: 60,
    price: 149,
    description: "RAM, SSD, and component upgrades",
    status: "active",
  },
  {
    id: "svc-7",
    name: "Virus Removal",
    category: "Software",
    duration: 60,
    price: 89,
    description: "Malware and virus removal with system cleanup",
    status: "active",
  },
  {
    id: "svc-8",
    name: "Water Damage Repair",
    category: "Repair",
    duration: 180,
    price: 199,
    description: "Water damage assessment and repair attempt",
    status: "inactive",
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: "inv-1",
    invoiceNumber: "INV-2024-001",
    clientId: "client-4",
    clientName: "David Kim",
    orderId: "order-4",
    orderNumber: "ORD-2024-004",
    amount: 449,
    status: "paid",
    dueDate: "2024-07-15",
    createdAt: "2024-07-02",
    paidAt: "2024-07-02",
  },
  {
    id: "inv-2",
    invoiceNumber: "INV-2024-002",
    clientId: "client-5",
    clientName: "Jessica Thompson",
    orderId: "order-5",
    orderNumber: "ORD-2024-005",
    amount: 149,
    status: "paid",
    dueDate: "2024-07-10",
    createdAt: "2024-06-30",
    paidAt: "2024-06-30",
  },
  {
    id: "inv-3",
    invoiceNumber: "INV-2024-003",
    clientId: "client-1",
    clientName: "Sarah Mitchell",
    orderId: "order-1",
    orderNumber: "ORD-2024-001",
    amount: 299,
    status: "sent",
    dueDate: "2024-07-15",
    createdAt: "2024-07-01",
  },
  {
    id: "inv-4",
    invoiceNumber: "INV-2024-004",
    clientId: "client-2",
    clientName: "Michael Chen",
    orderId: "order-2",
    orderNumber: "ORD-2024-002",
    amount: 199,
    status: "sent",
    dueDate: "2024-07-18",
    createdAt: "2024-07-01",
  },
  {
    id: "inv-5",
    invoiceNumber: "INV-2024-005",
    clientId: "client-6",
    clientName: "Robert Williams",
    amount: 500,
    status: "overdue",
    dueDate: "2024-06-25",
    createdAt: "2024-06-15",
  },
  {
    id: "inv-6",
    invoiceNumber: "INV-2024-006",
    clientId: "client-1",
    clientName: "Sarah Mitchell",
    orderId: "order-11",
    orderNumber: "ORD-2024-011",
    amount: 179,
    status: "paid",
    dueDate: "2024-07-10",
    createdAt: "2024-07-01",
    paidAt: "2024-07-01",
  },
  {
    id: "inv-7",
    invoiceNumber: "INV-2024-007",
    clientId: "client-9",
    clientName: "Lisa Chang",
    orderId: "order-9",
    orderNumber: "ORD-2024-009",
    amount: 49,
    status: "paid",
    dueDate: "2024-07-12",
    createdAt: "2024-07-02",
    paidAt: "2024-07-03",
  },
  {
    id: "inv-8",
    invoiceNumber: "INV-2024-008",
    clientId: "client-7",
    clientName: "Amanda Foster",
    amount: 249,
    status: "draft",
    dueDate: "2024-07-20",
    createdAt: "2024-07-03",
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: "txn-1",
    type: "income",
    category: "Service Revenue",
    description: "Payment for iPad Pro screen replacement",
    amount: 449,
    paymentMethod: "card",
    date: "2024-07-02",
    relatedOrderId: "order-4",
    relatedInvoiceId: "inv-1",
  },
  {
    id: "txn-2",
    type: "income",
    category: "Service Revenue",
    description: "Payment for Dell XPS software installation",
    amount: 149,
    paymentMethod: "cash",
    date: "2024-06-30",
    relatedOrderId: "order-5",
    relatedInvoiceId: "inv-2",
  },
  {
    id: "txn-3",
    type: "expense",
    category: "Inventory Purchase",
    description: "iPhone 14 Pro screens x5 from TechParts Direct",
    amount: 600,
    paymentMethod: "bank-transfer",
    date: "2024-07-01",
  },
  {
    id: "txn-4",
    type: "income",
    category: "Service Revenue",
    description: "Payment for Apple Watch screen replacement",
    amount: 179,
    paymentMethod: "card",
    date: "2024-07-01",
    relatedOrderId: "order-11",
    relatedInvoiceId: "inv-6",
  },
  {
    id: "txn-5",
    type: "expense",
    category: "Utilities",
    description: "Monthly electricity bill",
    amount: 245,
    paymentMethod: "bank-transfer",
    date: "2024-07-01",
  },
  {
    id: "txn-6",
    type: "expense",
    category: "Rent",
    description: "Monthly office rent",
    amount: 2500,
    paymentMethod: "bank-transfer",
    date: "2024-07-01",
  },
  {
    id: "txn-7",
    type: "income",
    category: "Service Revenue",
    description: "Payment for MacBook diagnostics",
    amount: 49,
    paymentMethod: "cash",
    date: "2024-07-03",
    relatedOrderId: "order-9",
    relatedInvoiceId: "inv-7",
  },
  {
    id: "txn-8",
    type: "expense",
    category: "Inventory Purchase",
    description: "MacBook Pro batteries x3 from Apple Parts Co",
    amount: 240,
    paymentMethod: "bank-transfer",
    date: "2024-06-28",
  },
  {
    id: "txn-9",
    type: "income",
    category: "Parts Sale",
    description: "USB-C Charger sale to walk-in customer",
    amount: 35,
    paymentMethod: "cash",
    date: "2024-07-02",
  },
  {
    id: "txn-10",
    type: "expense",
    category: "Marketing",
    description: "Google Ads monthly budget",
    amount: 350,
    paymentMethod: "card",
    date: "2024-07-01",
  },
];

// Helper functions for generating IDs
export function generateId(prefix: string): string {
  return `${prefix}-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
}

export function generateOrderNumber(): string {
  const count = mockOrders.length + 1;
  return `ORD-2024-${count.toString().padStart(3, "0")}`;
}

export function generateInvoiceNumber(): string {
  const count = mockInvoices.length + 1;
  return `INV-2024-${count.toString().padStart(3, "0")}`;
}
