import i18n from "../../i18n";
import type { Transaction } from "../../lib/types";

// Sample records for UI development only. They are not tied to any workspace and must never be
// combined with Supabase orders, clients or inventory. Built on call so the labels follow the UI language.
export function demoTransactions(): Transaction[] {
  const category = {
    serviceRevenue: i18n.t("finance.demo.categories.serviceRevenue"),
    inventoryPurchase: i18n.t("finance.demo.categories.inventoryPurchase"),
    utilities: i18n.t("finance.demo.categories.utilities"),
    rent: i18n.t("finance.demo.categories.rent"),
    partsSale: i18n.t("finance.demo.categories.partsSale"),
    marketing: i18n.t("finance.demo.categories.marketing"),
  };

  return [
    {
      id: "demo-txn-1",
      type: "income",
      category: category.serviceRevenue,
      description: i18n.t("finance.demo.descriptions.ipadScreen"),
      amount: 449,
      paymentMethod: "card",
      date: "2024-07-02",
      relatedOrderId: "demo-order-4",
      relatedInvoiceId: "demo-inv-1",
    },
    {
      id: "demo-txn-2",
      type: "income",
      category: category.serviceRevenue,
      description: i18n.t("finance.demo.descriptions.dellSoftware"),
      amount: 149,
      paymentMethod: "cash",
      date: "2024-06-30",
      relatedOrderId: "demo-order-5",
      relatedInvoiceId: "demo-inv-2",
    },
    {
      id: "demo-txn-3",
      type: "expense",
      category: category.inventoryPurchase,
      description: i18n.t("finance.demo.descriptions.iphoneScreens"),
      amount: 600,
      paymentMethod: "bank-transfer",
      date: "2024-07-01",
    },
    {
      id: "demo-txn-4",
      type: "income",
      category: category.serviceRevenue,
      description: i18n.t("finance.demo.descriptions.watchScreen"),
      amount: 179,
      paymentMethod: "card",
      date: "2024-07-01",
      relatedOrderId: "demo-order-11",
      relatedInvoiceId: "demo-inv-6",
    },
    {
      id: "demo-txn-5",
      type: "expense",
      category: category.utilities,
      description: i18n.t("finance.demo.descriptions.electricity"),
      amount: 245,
      paymentMethod: "bank-transfer",
      date: "2024-07-01",
    },
    {
      id: "demo-txn-6",
      type: "expense",
      category: category.rent,
      description: i18n.t("finance.demo.descriptions.rent"),
      amount: 2500,
      paymentMethod: "bank-transfer",
      date: "2024-07-01",
    },
    {
      id: "demo-txn-7",
      type: "income",
      category: category.serviceRevenue,
      description: i18n.t("finance.demo.descriptions.macbookDiagnostics"),
      amount: 49,
      paymentMethod: "cash",
      date: "2024-07-03",
      relatedOrderId: "demo-order-9",
      relatedInvoiceId: "demo-inv-7",
    },
    {
      id: "demo-txn-8",
      type: "expense",
      category: category.inventoryPurchase,
      description: i18n.t("finance.demo.descriptions.macbookBatteries"),
      amount: 240,
      paymentMethod: "bank-transfer",
      date: "2024-06-28",
    },
    {
      id: "demo-txn-9",
      type: "income",
      category: category.partsSale,
      description: i18n.t("finance.demo.descriptions.chargerSale"),
      amount: 35,
      paymentMethod: "cash",
      date: "2024-07-02",
    },
    {
      id: "demo-txn-10",
      type: "expense",
      category: category.marketing,
      description: i18n.t("finance.demo.descriptions.googleAds"),
      amount: 350,
      paymentMethod: "card",
      date: "2024-07-01",
    },
  ];
}
