import type { Transaction } from "../../lib/types";

// Sample records for UI development only. They are not tied to any workspace and must never be
// combined with Supabase orders, clients or inventory.
export const demoTransactions: Transaction[] = [
  {
    id: "demo-txn-1",
    type: "income",
    category: "Service Revenue",
    description: "Payment for iPad Pro screen replacement",
    amount: 449,
    paymentMethod: "card",
    date: "2024-07-02",
    relatedOrderId: "demo-order-4",
    relatedInvoiceId: "demo-inv-1",
  },
  {
    id: "demo-txn-2",
    type: "income",
    category: "Service Revenue",
    description: "Payment for Dell XPS software installation",
    amount: 149,
    paymentMethod: "cash",
    date: "2024-06-30",
    relatedOrderId: "demo-order-5",
    relatedInvoiceId: "demo-inv-2",
  },
  {
    id: "demo-txn-3",
    type: "expense",
    category: "Inventory Purchase",
    description: "iPhone 14 Pro screens x5 from TechParts Direct",
    amount: 600,
    paymentMethod: "bank-transfer",
    date: "2024-07-01",
  },
  {
    id: "demo-txn-4",
    type: "income",
    category: "Service Revenue",
    description: "Payment for Apple Watch screen replacement",
    amount: 179,
    paymentMethod: "card",
    date: "2024-07-01",
    relatedOrderId: "demo-order-11",
    relatedInvoiceId: "demo-inv-6",
  },
  {
    id: "demo-txn-5",
    type: "expense",
    category: "Utilities",
    description: "Monthly electricity bill",
    amount: 245,
    paymentMethod: "bank-transfer",
    date: "2024-07-01",
  },
  {
    id: "demo-txn-6",
    type: "expense",
    category: "Rent",
    description: "Monthly office rent",
    amount: 2500,
    paymentMethod: "bank-transfer",
    date: "2024-07-01",
  },
  {
    id: "demo-txn-7",
    type: "income",
    category: "Service Revenue",
    description: "Payment for MacBook diagnostics",
    amount: 49,
    paymentMethod: "cash",
    date: "2024-07-03",
    relatedOrderId: "demo-order-9",
    relatedInvoiceId: "demo-inv-7",
  },
  {
    id: "demo-txn-8",
    type: "expense",
    category: "Inventory Purchase",
    description: "MacBook Pro batteries x3 from Apple Parts Co",
    amount: 240,
    paymentMethod: "bank-transfer",
    date: "2024-06-28",
  },
  {
    id: "demo-txn-9",
    type: "income",
    category: "Parts Sale",
    description: "USB-C Charger sale to walk-in customer",
    amount: 35,
    paymentMethod: "cash",
    date: "2024-07-02",
  },
  {
    id: "demo-txn-10",
    type: "expense",
    category: "Marketing",
    description: "Google Ads monthly budget",
    amount: 350,
    paymentMethod: "card",
    date: "2024-07-01",
  },
];
