import { useRef, useState } from "react";
import { Button } from "../../ui/Button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "../../ui/Dialog";
import { Input } from "../../ui/Input";
import { Label } from "../../ui/Label";
import { formatSetupKey, totpQrSrc } from "../../services/authMessages";
import { cancelTotpEnrollment } from "../../services/apiMfa";
import type { TotpEnrollment } from "../../services/apiMfa";
import { useVerifyMfa } from "../auth/useMfa";

type EnableMfaDialogProps = {
  enrollment: TotpEnrollment | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onVerified: () => void;
};

export function EnableMfaDialog({ enrollment, open, onOpenChange, onVerified }: EnableMfaDialogProps) {
  const verifyMfa = useVerifyMfa();
  const verified = useRef(false);
  const closing = useRef(false);
  const [code, setCode] = useState("");
  const [error, setError] = useState("");
  const [cancelling, setCancelling] = useState(false);
  const verifying = verifyMfa.isPending;

  async function closeAndCancel() {
    if (!enrollment || cancelling || verified.current || closing.current) return;
    closing.current = true;
    setCancelling(true);
    try {
      await cancelTotpEnrollment(enrollment.factorId);
    } catch {
      // A later setup attempt removes any leftover unverified factor.
    } finally {
      setCancelling(false);
      setCode("");
      setError("");
      onOpenChange(false);
    }
  }

  async function verify(event: React.FormEvent) {
    event.preventDefault();
    if (!enrollment || verifying) return;
    setError("");
    try {
      await verifyMfa.mutateAsync({ factorId: enrollment.factorId, code });
      verified.current = true;
      setCode("");
      onVerified();
      onOpenChange(false);
    } catch (caught) {
      setError(caught instanceof Error ? caught.message : "Invalid verification code.");
    }
  }

  return (
    <Dialog
      open={open}
      onOpenChange={(next) => {
        if (next) {
          closing.current = false;
          return;
        }
        if (verified.current) {
          verified.current = false;
          onOpenChange(false);
          return;
        }
        void closeAndCancel();
      }}
    >
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle>Set up two-factor authentication</DialogTitle>
          <DialogDescription>Open your authenticator app and scan this QR code.</DialogDescription>
        </DialogHeader>
        {enrollment && (
          <form onSubmit={verify} className="space-y-4">
            <img src={totpQrSrc(enrollment.qrCode)} alt="Authenticator setup QR code" className="mx-auto h-48 w-48" />
            <div className="space-y-1">
              <p className="text-sm text-muted-foreground">Can&apos;t scan? Use this setup key:</p>
              <p className="break-all font-mono text-sm text-[#282e33]">{formatSetupKey(enrollment.secret)}</p>
            </div>
            <div className="space-y-2">
              <Label htmlFor="mfa-setup-code">Enter the 6-digit code generated by your authenticator app.</Label>
              <Input
                id="mfa-setup-code"
                inputMode="numeric"
                autoComplete="one-time-code"
                maxLength={6}
                value={code}
                disabled={verifying || cancelling}
                onChange={(event) => setCode(event.target.value.replace(/\D/g, "").slice(0, 6))}
                className="tracking-[0.4em]"
              />
              {error && <p className="text-xs text-[#f41f20]">{error}</p>}
            </div>
            <DialogFooter>
              <Button type="button" variant="outline" disabled={verifying || cancelling} onClick={() => void closeAndCancel()}>
                {cancelling ? "Cancelling..." : "Cancel"}
              </Button>
              <Button type="submit" disabled={verifying || cancelling || code.length !== 6}>
                {verifying ? "Verifying..." : "Verify and enable"}
              </Button>
            </DialogFooter>
          </form>
        )}
      </DialogContent>
    </Dialog>
  );
}
